name: C/C++ CI

on:
  push:
    branches:
    - dev
    - features/*
    
  pull_request:
    branches:
    - master
    - dev

env:
  BUILD_TYPE: Release
  
jobs:    
  build:
    name: Installing Vulkan SDK, updating submodules and building with CMake
    runs-on: windows-2019
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Installing Vulkan SDK
      uses: TWoolhouse/setup-vulkan-sdk@v1.1.0
      with:
        # SDK Version to install
        version: 1.3.211.0
        
    - name: Updating submodules
      run: git submodule update --init --recursive   
        
    - name : Setup CMake 
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.0'
        
    - name: CMake Version
      run: cmake --version
      
    - name: Creating Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configuring CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      # run: cmake $GITHUB_WORKSPACE -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=WIN64
      run: cmake -G "Visual Studio 16 2019" ../

    - name: Building
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -DAL_LIBTYPE_STATIC
      
    - name: Testing
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
